tests: exchange regexp and string with assert_match
MiniTest gem raises a TypeError
 TypeError: can't convert Regexp to String
when in assert_match the first argument is a string and the second a
regular expression, as the first argument is always converted to RegExp.